In [30]:
import pandas as pd
df = pd.read_parquet("/home/henri/ethos-benchmark/results/hospital_mortality/mimic_layer_6_do_0.3_recent_subset0.01_xzl337ud/rep_size_1_2026-09-17_15-14-57/samples_[0-3230).parquet")
df.iloc[:10:,:]

,expected,actual,stop_reason,actual_prob,HOSPITAL_DISCHARGE,MEDS_DEATH,TIMELINE_END,true_token_time,token_time,true_token_dist,token_dist,patient_id,prediction_time,data_idx,hadm_id,icu_stay_id
0,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.033688,3.368809e-02,5.638326e-06,1.376756e-04,1 days 16:04:00,0 days 00:00:00,92,1,11647046,2182-01-04 19:56:00,21583622,21048020,None
1,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.220218,2.202177e-01,3.462444e-05,1.606804e-06,1 days 16:04:00,0 days 03:49:12.313856,92,2,11647046,2182-01-04 19:56:00,21583622,21048020,None
2,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.274680,2.746804e-01,1.704511e-05,6.112426e-07,1 days 16:04:00,2 days 03:40:15.558272,92,17,11647046,2182-01-04 19:56:00,21583622,21048020,None
3,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.282660,2.826598e-01,2.062408e-06,3.473662e-07,1 days 16:04:00,0 days 11:41:27.722496,92,47,11647046,2182-01-04 19:56:00,21583622,21048020,None
4,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.225388,2.253882e-01,2.191778e-05,5.956093e-07,1 days 16:04:00,3 days 13:53:24.766720,92,173,11647046,2182-01-04 19:56:00,21583622,21048020,None
5,HOSPITAL_DISCHARGE,TIMELINE_END,token_of_interest,0.000051,5.482766e-08,1.444516e-07,5.063103e-05,1 days 14:53:00,0 days 03:21:00.346624,190,53,14653066,2128-07-10 02:55:00,8669206,28503793,None
6,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.765762,7.657624e-01,1.853058e-07,9.153667e-06,1 days 14:53:00,1 days 22:51:15.423360,190,212,14653066,2128-07-10 02:55:00,8669206,28503793,None
7,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.009064,9.064043e-03,4.672798e-06,1.458919e-06,1 days 14:53:00,2 days 01:56:13.429632,190,397,14653066,2128-07-10 02:55:00,8669206,28503793,None
8,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.430348,4.303479e-01,8.719477e-07,1.426411e-06,1 days 14:53:00,4 days 19:25:40.546752,190,653,14653066,2128-07-10 02:55:00,8669206,28503793,None
9,HOSPITAL_DISCHARGE,HOSPITAL_DISCHARGE,token_of_interest,0.052277,5.227746e-02,2.818474e-06,1.439536e-06,1 days 14:53:00,4 days 17:44:32.395776,190,1208,14653066,2128-07-10 02:55:00,8669206,28503793,None

In [24]:
df.sort_values(by="patient_id", ascending=True).iloc[900:1000:5,10:]

      token_dist  patient_id     prediction_time  data_idx     hadm_id
2190           9    13007657 2137-03-25 16:28:00  23961849  25296178.0
2274         169    13023241 2187-10-20 11:30:00  23989335  21597109.0
1203           2    13032738 2176-06-11 17:20:00  24002473  25158536.0
177           21    13051530 2174-06-10 18:49:00  24038786  22420878.0
176            1    13051530 2174-06-10 18:49:00  24038786  22420878.0
2204          42    13060229 2117-09-01 14:49:00  24079427  21728260.0
2602          58    13078497 2122-08-16 15:40:00   5710548  20907701.0
2066           9    13086918 2148-11-25 17:31:00   5729584  22599347.0
831            2    13102401 2148-07-09 15:57:00  24138411  26772369.0
1098           1    13102762 2171-11-21 19:45:00  42168887  22835343.0
349           49    13122237 2150-09-22 16:39:00  24171519  25954980.0
1870           1    13166078 2191-07-04 16:50:00   5869772  24536151.0
865            1    13175254 2196-09-29 23:02:00  42272156         NaN
2474          58    13182131 2183-05-23 11:27:00  42283131  24764032.0
2316           1    13187885 2152-12-13 17:00:00   5900366  21878541.0
2148           6    13189992 2140-03-20 13:50:00  42317523  27558504.0
461            1    13193522 2135-12-20 14:21:00  24265069  26877344.0
2568           1    13202370 2135-04-01 15:26:00  24279967  20970724.0
1942          24    13211934 2182-05-11 15:50:00  24282569  27371104.0
2383         367    13227740 2165-01-15 14:50:00  42384809  20295496.0

In [31]:
df.shape

(3230, 16)

In [33]:
df[df.expected.str.contains("DEATH")].shape

(70, 16)