In [9]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

import polars as pl
from matplotlib import pyplot as plt

from ethos.constants import PROJECT_ROOT
from ethos.constants import SpecialToken as ST
from ethos.inference.constants import Task
from ethos.metrics import compute_and_print_metrics, preprocess_inference_results
from ethos.utils import get_mimic_hf_patients

# Requires original MIMIC-IV 2.2 dataset that we do not provide
result_dir = PROJECT_ROOT / "results" / Task.READMISSION
# heart_failure_cohort = get_mimic_hf_patients(PROJECT_ROOT / "data/mimic-2.2")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
# DEBUGGING ONLY
import sys
project_root = Path.cwd()
while not (project_root / 'pyproject.toml').exists() and project_root != project_root.parent:
    project_root = project_root.parent

sys.path.insert(0, str(project_root))
from src.ethos.datasets.readmission import ReadmissionDataset, ReadmissionDatasetOld
path = "../../../../mnt/data_share/project_henri/ethos-ares/mimic-tokenized/test"
dataset = ReadmissionDataset(path)
sum_adm = sum([True if (d[1]['expected'] == 'HOSPITAL_ADMISSION' and d[1]['true_token_time'] <= (dataset.time_limit.total_seconds() * 1e6)) else False for d in dataset])
sum_adm#/len(dataset)

432 deaths before discharge
3 discharges before admission
21301 start indices

4441

In [13]:
import json
true_ids = [d[1]['hadm_id'] for d in dataset if (d[1]['expected'] == 'HOSPITAL_ADMISSION' and d[1]['true_token_time'] <= (dataset.time_limit.total_seconds() * 1e6))]
with open("true_ids.json", "w") as f:
    json.dump(true_ids, f)

In [7]:
for i in range(len(dataset)): 
    if dataset[i][1]['hadm_id'] == 26093647:
        print(i, dataset[i][1])
        print(f"True token time under 30 days: {dataset[i][1]['true_token_time'] <= (dataset.time_limit.total_seconds() * 1e6)}")
        break

16110 {'expected': 'HOSPITAL_ADMISSION', 'true_token_dist': 180, 'true_token_time': 662520000000, 'patient_id': 17848200, 'prediction_time': 6812294400000000, 'data_idx': 13924168, 'hadm_id': 26093647}
True token time under 30 days: True

In [5]:
import pandas as pd
df_token = pd.read_parquet(f"{path}/14_inject_time_intervals/0.parquet")

In [6]:
df_id = df_token[df_token['subject_id'].isin([13529462])]
df_id[df_id.code.str.contains('HOSPITAL') | df_id.code.str.contains('DEATH') | df_id.code.str.contains('TIMELINE')]

Empty DataFrame
Columns: [subject_id, time, code, numeric_value, text_value, hadm_id, edstay_id, icustay_id, insurance, language, marital_status, race, drg_severity, drg_mortality, emar_id, emar_seq, priority]
Index: []

In [20]:
df_token[df_token['subject_id'] == 18160222].iloc[-10:]

,subject_id,time,code,numeric_value,text_value,hadm_id,edstay_id,icustay_id,insurance,language,marital_status,race,drg_severity,drg_mortality,emar_id,emar_seq,priority
15279750,18160222,2138-06-15 13:30:00,ICD//CM//RETENTION_OF_URINE,NaN,R339,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279751,18160222,2138-06-15 13:30:00,ICD//CM//3-6//9,NaN,R339,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279752,18160222,2138-06-15 13:30:00,ICD//CM//OTHER_DISORDERS_OF_BRAIN,NaN,G93,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279753,18160222,2138-06-15 13:30:00,ICD//CM//PLACE_OF_OCCURRENCE_OF_THE_EXTERNAL_C...,NaN,Y92199,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279754,18160222,2138-06-15 13:30:00,ICD//CM//3-6//199,NaN,Y92199,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279755,18160222,2138-06-15 13:30:00,ICD//CM//ACQUIRED_ABSENCE_OF_ORGANS_NOT_ELSEWH...,NaN,Z90710,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279756,18160222,2138-06-15 13:30:00,ICD//CM//3-6//710,NaN,Z90710,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279757,18160222,2138-06-15 13:30:00,ICD//CM//OTHER_SPONDYLOPATHIES,NaN,M4800,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279758,18160222,2138-06-15 13:30:00,ICD//CM//3-6//00,NaN,M4800,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15279759,18160222,2138-06-15 13:30:00,TIMELINE_END,NaN,M4800,29276603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_token[df_token.code.str.contains('_DISCHARGE')].iloc[:10]

,subject_id,time,code,numeric_value,text_value,hadm_id,edstay_id,icustay_id,insurance,language,marital_status,race,drg_severity,drg_mortality,emar_id,emar_seq,priority
14,10000068,2160-03-04 06:26:00,HOSPITAL_DISCHARGE,NaN,UNK,25022803.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,10002155,2128-07-31 18:00:00,HOSPITAL_DISCHARGE,NaN,HOME,28439444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,10002155,2129-08-10 17:02:38,ICU_DISCHARGE,NaN,ICU_TYPE//Coronary Care Unit (CCU),23822395.0,NaN,33685454.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1280,10002155,2129-08-18 16:53:00,HOSPITAL_DISCHARGE,NaN,CHRONIC/LONG TERM ACUTE CARE,23822395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,10002155,2129-12-25 19:18:00,HOSPITAL_DISCHARGE,NaN,HOME HEALTH CARE,28976727.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2898,10002155,2130-09-27 22:13:41,ICU_DISCHARGE,NaN,ICU_TYPE//Medical/Surgical Intensive Care Unit...,28994087.0,NaN,31090461.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2941,10002155,2130-09-29 18:55:00,HOSPITAL_DISCHARGE,NaN,HOME HEALTH CARE,28994087.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3539,10002155,2131-03-10 18:09:21,HOSPITAL_DISCHARGE,NaN,DIED,20345487.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3543,10002155,2131-03-10 18:09:21,ICU_DISCHARGE,NaN,ICU_TYPE//Medical Intensive Care Unit (MICU),20345487.0,NaN,32358465.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3889,10002804,2148-09-28 12:10:00,HOSPITAL_DISCHARGE,NaN,HOME,20769698.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_token.iloc[5739:5748]

,subject_id,time,code,numeric_value,text_value,hadm_id,edstay_id,icustay_id,insurance,language,marital_status,race,drg_severity,drg_mortality,emar_id,emar_seq,priority
5739,10002930,2197-04-08 18:16:00,Q1,0.0,0,NaN,38615683.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5740,10002930,2197-04-08 19:37:00,1h15m-2h,NaN,UNK,28477649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5741,10002930,2197-04-08 19:37:00,HOSPITAL_DISCHARGE,NaN,UNK,28477649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5742,10002930,2197-04-08 19:37:00,DISCHARGE_LOCATION//UNK,NaN,UNK,28477649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5743,10002930,2197-04-08 19:37:00,HOSPITAL_ADMISSION,NaN,URGENT,28301173.0,NaN,NaN,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,NaN,NaN,NaN,NaN,NaN
5744,10002930,2197-04-08 19:37:00,ADMISSION_TYPE//EMERGENCY,NaN,URGENT,28301173.0,NaN,NaN,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,NaN,NaN,NaN,NaN,NaN
5745,10002930,2197-04-08 19:37:00,INSURANCE//MEDICARE,NaN,URGENT,28301173.0,NaN,NaN,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,NaN,NaN,NaN,NaN,NaN
5746,10002930,2197-04-08 19:37:00,ICD//CM//UNSPECIFIED_PSYCHOSIS_NOT_DUE_TO_A_SU...,NaN,F29,28477649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5747,10002930,2197-04-08 19:37:00,ICD//CM//SYMPTOMS_AND_SIGNS_INVOLVING_EMOTIONA...,NaN,R45851,28477649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def compute_readmission_results(input_dir: Path, outcome_tokens: list[str]) -> pl.DataFrame:
    # outcome_tokens = [str(st) for st in outcome_tokens]
    return preprocess_inference_results(
        input_dir,
        actual_expr=pl.col("actual").is_in(outcome_tokens),
        expected_expr=(
            pl.col("expected").is_in(outcome_tokens)
            & (pl.col("true_token_time") <= pl.duration(days=30))
        ),
    )


def evaluate_readmission_results(input_dir: Path) -> dict:
    # df = compute_readmission_results(input_dir, outcome_tokens=[ST.ADMISSION, ST.DEATH])
    df = compute_readmission_results(input_dir, outcome_tokens=[ST.ADMISSION])

    fig = plt.figure(figsize=(5, 5))
    rep_num = df["counts"].mean()
    fig.suptitle(f"30-Day Readmission (rep_num={rep_num:.2f})\n{input_dir.name}")

    plt.subplot(1, 1, 1)
    res_full = compute_and_print_metrics(df["expected"], df["actual"], "Full")

    # Here, we leave samples where the history (gt) spans for 30 days
    '''reduced_df = df.filter(
        (pl.col("expected") == 1)
        | ((pl.col("expected") == 0) & (pl.col("true_token_time") >= pl.duration(days=30)))
    )
    plt.subplot(1, 3, 2)
    res_reduced = compute_and_print_metrics(reduced_df["expected"], reduced_df["actual"], "Reduced")'''

    # plt.subplot(1, 3, 3)
    '''hearth_failure_df = df.filter(pl.col("patient_id").is_in(heart_failure_cohort))
    res_hf = compute_and_print_metrics(
        hearth_failure_df["expected"], hearth_failure_df["actual"], "HF patients"
    )'''

    return {
        "name": input_dir.name,
        "auc_full": res_full["fitted_auc"],
        # "auc_reduced": res_reduced["fitted_auc"],
        # "auc_hf": res_hf["fitted_auc"],
        "rep_num": rep_num,
    }

In [ ]:
readmission_results = []
for result_fp in result_dir.iterdir():
    readmission_results.append(evaluate_readmission_results(result_fp))
    plt.tight_layout()
readmission_results = pl.from_dicts(readmission_results).sort("auc_full", descending=True)

In [ ]:
readmission_results.sort("auc_full", descending=True)