In [1]:
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import polars as pl

from ethos.constants import PROJECT_ROOT
from ethos.constants import SpecialToken as ST
from ethos.inference.constants import Reason, Task
from ethos.metrics import compute_and_print_metrics, preprocess_inference_results

results_dir = PROJECT_ROOT / "results"

## Hospital Admission results

In [2]:
def process_hosp_admission_results(input_dir, **kwargs) -> pl.DataFrame:
    return preprocess_inference_results(
        input_dir,
        actual_expr=pl.col("actual").is_in([ST.ADMISSION]),
        expected_expr=pl.col("expected").is_in([ST.ADMISSION]),
        filter_ambiguous=pl.col("stop_reason") == Reason.GOT_TOKEN,
        **kwargs,
    )

In [2]:
# DEBUGGING ONLY
import sys
from pathlib import Path

project_root = Path.cwd()
while not (project_root / 'pyproject.toml').exists() and project_root != project_root.parent:
    project_root = project_root.parent

sys.path.insert(0, str(project_root))
from src.ethos.datasets.ed import HospitalAdmissionAtTriageDataset
path = "../data/mimic-tokenized/test"
dataset = HospitalAdmissionAtTriageDataset(path)
sum_adm = sum([d[1]['expected'] for d in dataset])
sum_adm, len(dataset), sum_adm / len(dataset)

ValueError: shard_fps: [PosixPath('../data/mimic-tokenized/test/0.safetensors'), PosixPath('../data/mimic-tokenized/test/1.safetensors'), PosixPath('../data/mimic-tokenized/test/2.safetensors')]

In [3]:
hosp_admission_results = []
for input_dir in (results_dir / Task.ED_HOSPITALIZATION).iterdir():
    df = process_hosp_admission_results(input_dir)
    rep_num = df["counts"].mean()
    res = compute_and_print_metrics(
        df["expected"],
        df["actual"],
        f"Hospital Admission (rep_num={rep_num:.2f})\n{input_dir.name}",
    )
    hosp_admission_results.append(
        {
            "name": input_dir.name,
            "auc": res["fitted_auc"],
            "rep_num": rep_num,
        }
    )
    plt.show()
hosp_admission_results = pl.DataFrame(hosp_admission_results).sort("auc", descending=True)

2026-10-21 11:10:11.190 | WARNING  | ethos.metrics:preprocess_inference_results:315 - Dropped 2 results due to stop reason: key_error.
2026-10-21 11:10:11.201 | WARNING  | ethos.metrics:preprocess_inference_results:321 - Dropped 59,535 (7.75%) ambiguous results.

InvalidOperationError: 'is_in' cannot check for Enum(Some(local), Physical) values in Boolean data

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
 WITH_COLUMNS:
 [col("actual").is_in([Series]).alias("actual"), col("expected").is_in([Series]).alias("expected")]
  DF ["expected", "actual", "stop_reason", "actual_prob", ...]; PROJECT */15 COLUMNS

In [4]:
import pandas as pd
df_ha = pd.read_parquet("/home/hb101@hsg.privat/ethos-benchmark/results/ed_hospitalization/mimic_layer_6_do_0.3_best_d0uj0vfx/rep_size_20_2026-10-19_11-43-04/samples_[0-128000).parquet")

In [5]:
df_ha.head()

,expected,actual,stop_reason,actual_prob,HOSPITAL_ADMISSION,MEDS_DEATH,TIMELINE_END,true_token_time,token_time,true_token_dist,token_dist,patient_id,hadm_id,prediction_time,data_idx
0,False,TIMELINE_END,token_of_interest,0.192514,4.087801e-07,9.504421e-07,0.192514,-5991 days +06:31:00,0 days 01:58:19.184640,166,29,10618238,NaN,2144-01-06 18:47:00,19729468
1,False,TIMELINE_END,token_of_interest,0.120064,5.656151e-07,2.193782e-06,0.120064,-5991 days +06:31:00,366 days 18:56:14.649984,166,34,10618238,NaN,2144-01-06 18:47:00,19729468
2,False,TIMELINE_END,token_of_interest,0.172161,1.246571e-05,9.937046e-07,0.172161,-5991 days +06:31:00,0 days 04:48:21.906176,166,37,10618238,NaN,2144-01-06 18:47:00,19729468
3,False,TIMELINE_END,token_of_interest,0.704670,1.402887e-06,6.524031e-07,0.704670,-5991 days +06:31:00,0 days 05:34:12.111552,166,55,10618238,NaN,2144-01-06 18:47:00,19729468
4,False,TIMELINE_END,token_of_interest,0.146849,7.794413e-06,2.992405e-08,0.146849,-5991 days +06:31:00,0 days 03:48:59.860288,166,60,10618238,NaN,2144-01-06 18:47:00,19729468

In [6]:
import pandas as pd
df_raw = pd.read_parquet("/home/hb101@hsg.privat/ethos-benchmark/data/mimic-tokenized/test/11_inject_time_intervals/0.parquet")

In [10]:
df_raw.iloc[30:40]

,subject_id,time,code,numeric_value,text_value,hadm_id,edstay_id,icustay_id,insurance,language,marital_status,race,drg_severity,drg_mortality,emar_id,emar_seq,priority
30,10000951,2155-09-30 20:15:00,Q1,57.0,101/57.0,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,10000951,2155-09-30 20:15:00,VITAL//PAIN,5.0,5,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,10000951,2155-09-30 20:15:00,Q3,5.0,5,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,10000951,2155-09-30 20:15:00,ACUITY,3.0,NaN,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,10000951,2155-09-30 20:15:00,Q3,3.0,NaN,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,10000951,2155-09-30 20:15:00,VITAL//BLOOD_PRESSURE,NaN,101/57,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,10000951,2155-09-30 20:15:00,Q1,101.0,101/57,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,10000951,2155-09-30 20:15:00,Q1,57.0,101/57,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,10000951,2155-09-30 20:15:00,ED_REGISTRATION,NaN,WALK IN,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,10000951,2155-09-30 20:15:00,ED_TRANSPORT//WALK_IN,NaN,WALK IN,NaN,35942449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
hosp_admission_results